### ISSUE TITLE
wrong controller

### ISSUE THREAD

**Issue by achasveachas** [learn-co-curriculum/sinatra-secure-password-lab#16]
the starter code on this lab comes with an '/success' controller that redirects to success.erb when it's supposed to be a '/account' controller going to account.erb.

My guess is that it was simply copied from the previous lab (sinatra-password-security-v-000) and wasn't updated accordingly.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback @achasveachas!

We have updated the materials and believe your issue to have been resolved in both branches.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
