### ISSUE TITLE
Fix solution

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/sinatra-secure-password-lab#21]
Update solution code to use `session[:user_id]` and memoization.

**Comment by DanielSeehausen** [comment]
Hey @Lukeghenco you 3 spaces in each tab madman!
I am going to close this for now. If you have more information on what you would like changed, please re-open and just let us know OR feel free to pull the code in yourself! I am something of a n0013 and unable to interpret exactly what you would like changed :(.

**Comment by Lukeghenco** [comment]
Yea, no idea what this was about. Thanks @DanielSeehausen and your the one who uses 3 spaces :) .
