### ISSUE TITLE
Gemfile not setup correctly

### ISSUE THREAD

**Issue by coryjbergquist** [learn-co-curriculum/sinatra-secure-password-lab#24]
Need to change: gem 'activerecord' 
to: gem 'activerecord', '4.2', :require => 'active_record'

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
