### ISSUE TITLE
Need to move pry up in gemfile

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/sinatra-secure-password-lab#26]
When running learn and shotgun, you can't hit pry unless you move it up in the gemfile as shown:
```
gem 'shotgun'
gem 'pry'

group :development do
  gem 'sqlite3'
  gem 'rspec'
  gem 'tux'
end
```

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
